/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'other' : IDL.Null,
  'milk' : IDL.Null,
  'tea_powder' : IDL.Null,
  'snacks' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'shopName' : IDL.Text,
});
export const Time = IDL.Int;
export const StockEntry = IDL.Record({
  'date' : Time,
  'unit' : IDL.Text,
  'costAmount' : IDL.Nat,
  'itemName' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : Category,
});
export const SaleEntry = IDL.Record({
  'totalSalesAmount' : IDL.Nat,
  'date' : Time,
});
export const DashboardData = IDL.Record({
  'stockEntries' : IDL.Vec(StockEntry),
  'totalInvestment' : IDL.Nat,
  'profitLoss' : IDL.Int,
  'totalSales' : IDL.Nat,
  'saleEntries' : IDL.Vec(SaleEntry),
});
export const Shop = IDL.Record({
  'pin' : IDL.Nat,
  'ownerName' : IDL.Text,
  'name' : IDL.Text,
  'mobileNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSaleEntry' : IDL.Func([IDL.Nat], [], []),
  'addSaleEntryByMobile' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addStockEntry' : IDL.Func(
      [Category, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'addStockEntryByMobile' : IDL.Func(
      [IDL.Text, Category, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardData' : IDL.Func([Time, Time], [DashboardData], ['query']),
  'getDashboardDataByMobile' : IDL.Func(
      [IDL.Text, Time, Time],
      [DashboardData],
      ['query'],
    ),
  'getMonthlyDashboard' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [DashboardData],
      ['query'],
    ),
  'getMonthlyDashboardByMobile' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [DashboardData],
      ['query'],
    ),
  'getShopInfo' : IDL.Func([], [IDL.Opt(Shop)], ['query']),
  'getShopInfoByMobile' : IDL.Func([IDL.Text], [IDL.Opt(Shop)], ['query']),
  'getUserProfileByMobile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'loginByMobile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'registerShop' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'requestOtp' : IDL.Func([IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'other' : IDL.Null,
    'milk' : IDL.Null,
    'tea_powder' : IDL.Null,
    'snacks' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'shopName' : IDL.Text,
  });
  const Time = IDL.Int;
  const StockEntry = IDL.Record({
    'date' : Time,
    'unit' : IDL.Text,
    'costAmount' : IDL.Nat,
    'itemName' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : Category,
  });
  const SaleEntry = IDL.Record({ 'totalSalesAmount' : IDL.Nat, 'date' : Time });
  const DashboardData = IDL.Record({
    'stockEntries' : IDL.Vec(StockEntry),
    'totalInvestment' : IDL.Nat,
    'profitLoss' : IDL.Int,
    'totalSales' : IDL.Nat,
    'saleEntries' : IDL.Vec(SaleEntry),
  });
  const Shop = IDL.Record({
    'pin' : IDL.Nat,
    'ownerName' : IDL.Text,
    'name' : IDL.Text,
    'mobileNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSaleEntry' : IDL.Func([IDL.Nat], [], []),
    'addSaleEntryByMobile' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addStockEntry' : IDL.Func(
        [Category, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'addStockEntryByMobile' : IDL.Func(
        [IDL.Text, Category, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardData' : IDL.Func([Time, Time], [DashboardData], ['query']),
    'getDashboardDataByMobile' : IDL.Func(
        [IDL.Text, Time, Time],
        [DashboardData],
        ['query'],
      ),
    'getMonthlyDashboard' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [DashboardData],
        ['query'],
      ),
    'getMonthlyDashboardByMobile' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [DashboardData],
        ['query'],
      ),
    'getShopInfo' : IDL.Func([], [IDL.Opt(Shop)], ['query']),
    'getShopInfoByMobile' : IDL.Func([IDL.Text], [IDL.Opt(Shop)], ['query']),
    'getUserProfileByMobile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'loginByMobile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'registerShop' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'requestOtp' : IDL.Func([IDL.Text], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };