/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'other' : null } |
  { 'milk' : null } |
  { 'tea_powder' : null } |
  { 'snacks' : null };
export interface DashboardData {
  'stockEntries' : Array<StockEntry>,
  'totalInvestment' : bigint,
  'profitLoss' : bigint,
  'totalSales' : bigint,
  'saleEntries' : Array<SaleEntry>,
}
export interface SaleEntry { 'totalSalesAmount' : bigint, 'date' : Time }
export interface Shop {
  'pin' : bigint,
  'ownerName' : string,
  'name' : string,
  'mobileNumber' : string,
}
export interface StockEntry {
  'date' : Time,
  'unit' : string,
  'costAmount' : bigint,
  'itemName' : string,
  'quantity' : bigint,
  'category' : Category,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'mobileNumber' : string,
  'shopName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSaleEntry' : ActorMethod<[bigint], undefined>,
  'addSaleEntryByMobile' : ActorMethod<[string, bigint], undefined>,
  'addStockEntry' : ActorMethod<
    [Category, string, bigint, string, bigint],
    undefined
  >,
  'addStockEntryByMobile' : ActorMethod<
    [string, Category, string, bigint, string, bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardData' : ActorMethod<[Time, Time], DashboardData>,
  'getDashboardDataByMobile' : ActorMethod<[string, Time, Time], DashboardData>,
  'getMonthlyDashboard' : ActorMethod<[bigint, bigint], DashboardData>,
  'getMonthlyDashboardByMobile' : ActorMethod<
    [string, bigint, bigint],
    DashboardData
  >,
  'getShopInfo' : ActorMethod<[], [] | [Shop]>,
  'getShopInfoByMobile' : ActorMethod<[string], [] | [Shop]>,
  'getUserProfileByMobile' : ActorMethod<[string], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string, string], boolean>,
  'loginByMobile' : ActorMethod<[string, string], boolean>,
  'registerShop' : ActorMethod<[string, string, string], undefined>,
  'requestOtp' : ActorMethod<[string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];