/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface DashboardData {
    stockEntries: Array<StockEntry>;
    totalInvestment: bigint;
    profitLoss: bigint;
    totalSales: bigint;
    saleEntries: Array<SaleEntry>;
}
export interface SaleEntry {
    totalSalesAmount: bigint;
    date: Time;
}
export interface Shop {
    pin: bigint;
    ownerName: string;
    name: string;
    mobileNumber: string;
}
export interface UserProfile {
    name: string;
    mobileNumber: string;
    shopName: string;
}
export interface StockEntry {
    date: Time;
    unit: string;
    costAmount: bigint;
    itemName: string;
    quantity: bigint;
    category: Category;
}
export enum Category {
    other = "other",
    milk = "milk",
    tea_powder = "tea_powder",
    snacks = "snacks"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addSaleEntry(totalSalesAmount: bigint): Promise<void>;
    addSaleEntryByMobile(mobileNumber: string, totalSalesAmount: bigint): Promise<void>;
    addStockEntry(category: Category, itemName: string, quantity: bigint, unit: string, costAmount: bigint): Promise<void>;
    addStockEntryByMobile(mobileNumber: string, category: Category, itemName: string, quantity: bigint, unit: string, costAmount: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardData(startDate: Time, endDate: Time): Promise<DashboardData>;
    getDashboardDataByMobile(mobileNumber: string, startDate: Time, endDate: Time): Promise<DashboardData>;
    getMonthlyDashboard(year: bigint, month: bigint): Promise<DashboardData>;
    getMonthlyDashboardByMobile(mobileNumber: string, year: bigint, month: bigint): Promise<DashboardData>;
    getShopInfo(): Promise<Shop | null>;
    getShopInfoByMobile(mobileNumber: string): Promise<Shop | null>;
    getUserProfileByMobile(mobileNumber: string): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    login(mobileNumber: string, otp: string): Promise<boolean>;
    loginByMobile(mobileNumber: string, otp: string): Promise<boolean>;
    registerShop(name: string, ownerName: string, mobileNumber: string): Promise<void>;
    requestOtp(mobileNumber: string): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { Category as _Category, DashboardData as _DashboardData, SaleEntry as _SaleEntry, Shop as _Shop, StockEntry as _StockEntry, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addSaleEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSaleEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSaleEntry(arg0);
            return result;
        }
    }
    async addSaleEntryByMobile(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSaleEntryByMobile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSaleEntryByMobile(arg0, arg1);
            return result;
        }
    }
    async addStockEntry(arg0: Category, arg1: string, arg2: bigint, arg3: string, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStockEntry(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStockEntry(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addStockEntryByMobile(arg0: string, arg1: Category, arg2: string, arg3: bigint, arg4: string, arg5: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addStockEntryByMobile(arg0, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStockEntryByMobile(arg0, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardData(arg0: Time, arg1: Time): Promise<DashboardData> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardData(arg0, arg1);
                return from_candid_DashboardData_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardData(arg0, arg1);
            return from_candid_DashboardData_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardDataByMobile(arg0: string, arg1: Time, arg2: Time): Promise<DashboardData> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardDataByMobile(arg0, arg1, arg2);
                return from_candid_DashboardData_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardDataByMobile(arg0, arg1, arg2);
            return from_candid_DashboardData_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyDashboard(arg0: bigint, arg1: bigint): Promise<DashboardData> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyDashboard(arg0, arg1);
                return from_candid_DashboardData_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyDashboard(arg0, arg1);
            return from_candid_DashboardData_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyDashboardByMobile(arg0: string, arg1: bigint, arg2: bigint): Promise<DashboardData> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyDashboardByMobile(arg0, arg1, arg2);
                return from_candid_DashboardData_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyDashboardByMobile(arg0, arg1, arg2);
            return from_candid_DashboardData_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShopInfo(): Promise<Shop | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShopInfo();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShopInfo();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShopInfoByMobile(arg0: string): Promise<Shop | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShopInfoByMobile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShopInfoByMobile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfileByMobile(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfileByMobile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfileByMobile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return result;
        }
    }
    async loginByMobile(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.loginByMobile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginByMobile(arg0, arg1);
            return result;
        }
    }
    async registerShop(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerShop(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerShop(arg0, arg1, arg2);
            return result;
        }
    }
    async requestOtp(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.requestOtp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestOtp(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_Category_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_DashboardData_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardData): DashboardData {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_StockEntry_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StockEntry): StockEntry {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Shop]): Shop | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: _Time;
    unit: string;
    costAmount: bigint;
    itemName: string;
    quantity: bigint;
    category: _Category;
}): {
    date: Time;
    unit: string;
    costAmount: bigint;
    itemName: string;
    quantity: bigint;
    category: Category;
} {
    return {
        date: value.date,
        unit: value.unit,
        costAmount: value.costAmount,
        itemName: value.itemName,
        quantity: value.quantity,
        category: from_candid_Category_n13(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stockEntries: Array<_StockEntry>;
    totalInvestment: bigint;
    profitLoss: bigint;
    totalSales: bigint;
    saleEntries: Array<_SaleEntry>;
}): {
    stockEntries: Array<StockEntry>;
    totalInvestment: bigint;
    profitLoss: bigint;
    totalSales: bigint;
    saleEntries: Array<SaleEntry>;
} {
    return {
        stockEntries: from_candid_vec_n10(_uploadFile, _downloadFile, value.stockEntries),
        totalInvestment: value.totalInvestment,
        profitLoss: value.profitLoss,
        totalSales: value.totalSales,
        saleEntries: value.saleEntries
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    milk: null;
} | {
    tea_powder: null;
} | {
    snacks: null;
}): Category {
    return "other" in value ? Category.other : "milk" in value ? Category.milk : "tea_powder" in value ? Category.tea_powder : "snacks" in value ? Category.snacks : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StockEntry>): Array<StockEntry> {
    return value.map((x)=>from_candid_StockEntry_n11(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    other: null;
} | {
    milk: null;
} | {
    tea_powder: null;
} | {
    snacks: null;
} {
    return value == Category.other ? {
        other: null
    } : value == Category.milk ? {
        milk: null
    } : value == Category.tea_powder ? {
        tea_powder: null
    } : value == Category.snacks ? {
        snacks: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
